// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[forward-0]
	_ = x[down-1]
	_ = x[up-2]
	_ = x[invalid-3]
}

const _Opcode_name = "forwarddownupinvalid"

var _Opcode_index = [...]uint8{0, 7, 11, 13, 20}

func (i Opcode) String() string {
	if i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
